### ISSUE TITLE
ruby installation issues on linux?

### ISSUE THREAD

**Issue by rossmounce** [willpearse/phyloGenerator2#11]
(`mafft` & `raxml` already installed / executable. Not sure how pg2 will 'find' my raxml though...)

```
sudo gem install bio
[sudo] password for ross: 
Fetching: bio-1.5.1.gem (100%)
Successfully installed bio-1.5.1
Parsing documentation for bio-1.5.1
Installing ri documentation for bio-1.5.1
Done installing documentation for bio after 8 seconds
1 gem installed
```

```
$ ./pG_2.rb ./demo/simple_plants/params.yml 
Ignoring escape_utils-1.1.0 because its extensions are not built.  Try: gem pristine escape_utils --version 1.1.0
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bio (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ross/workspace/phyloGenerator2/lib/Download.rb:6:in `<top (required)>'
	from /home/ross/workspace/phyloGenerator2/lib/Cap.rb:2:in `require_relative'
	from /home/ross/workspace/phyloGenerator2/lib/Cap.rb:2:in `<top (required)>'
	from ./pG_2.rb:6:in `require_relative'
	from ./pG_2.rb:6:in `<main>'

```

**Comment by willpearse** [comment]
If a program called ```raxml``` is in your $PATH (this is the case if you've ```apt install mafft``` for MAFFT, then it will all be fine.

It sounds like this is something quite profound going wrong with your ruby installation. At the risk of sounding a bit difficult, I would suggest making sure you've got that installed cleanly. As a quick test, what happens if you start Ruby interactively (```irb```) and then type into the console ```require "bio"```?

I would also try ```sudo apt install ruby-dev``` and then re-running ```sudo gem install bio```. Something very peculiar is going on, but hopefully re-running those with the dev tools will fix this. Have you used Ruby before? It sounds like you might have done something with your runtime environment (http://stackoverflow.com/questions/38797458/ignoring-gem-because-its-extensions-are-not-built)

I've sent you an email with a more detailed installation guide that I used in a session I ran recently, in case that's useful. Thanks again for looking at this Ross.

**Comment by rossmounce** [comment]
Got the simple plants demo working :)

FYI, I think it required `gem install bio` NOT `sudo gem install bio` for my installation.

Perhaps RVM might be an idea? I know NVM saves my ass with similar node package issues
http://stackoverflow.com/questions/2119064/sudo-gem-install-or-gem-install-and-gem-locations

**Comment by willpearse** [comment]
Good :D we're good for tomorrow then!... :D

You're right. I'll leave sudo "to the people" :p
